name: toreminder
description: A Todo Management app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # calendar_timeline:
  #    path: ./packages/calendar_timeline
  connectivity_plus: ^2.1.0
  device_preview: ^1.0.0
  # dotted_border: ^2.0.0+2
  # fl_chart: ^0.45.1
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.2
  flutter_slidable: ^1.1.0
  # flutter_staggered_grid_view: ^0.4.1
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.0.0
  grouped_list: ^4.2.0
  # hooks_riverpod: ^1.0.2
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  # intl: ^0.17.0
  # lottie: ^1.2.1
  # metadata_fetch: ^0.4.1
  responsive_framework: ^0.1.7
  shared_preferences: ^2.0.9
  sqflite: ^2.0.2
  # timeago: ^3.1.0

  # Errors Handling:
  sentry_flutter: ^6.4.0
  
  # Widgets:
  fluttertoast: ^8.0.9
    
  # Packages:
  auth:
    path: packages/auth

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  freezed: ^1.0.0
  json_serializable: ^6.1.1
  
  # Testing:
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
    
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  adaptive_icon_background: "#9B60EC"
  adaptive_icon_foreground: "assets/logo-fg.png"
    
flutter_native_splash:
  color: "#151515"
  image: assets/splash.png
  android_gravity: center
  branding: assets/branding.png
  branding_mode: bottom

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Bree
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf
